In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("../data/processed/customer_churn_feature_engineered.csv")

df.head()

,CustomerID,Gender,Age,SeniorCitizen,Partner,Dependents,TenureMonths,PhoneService,InternetService,OnlineSecurity,...,PaymentMethod,MonthlyCharges,TotalCharges,SupportTickets,SatisfactionScore,Churn,TenureGroup,MonthlyChargeCategory,SupportLevel,AverageMonthlySpend
0,CUST000001,Female,19,0,Yes,Yes,14,Yes,Cable,No,...,Electronic Check,63.94,902.51,2,5,Yes,1-2 Years,Medium,Medium,64.465000
1,CUST000002,Female,55,0,Yes,No,57,No,Fiber Optic,No,...,Electronic Check,72.51,4116.15,0,3,No,4-6 Years,High,Low,72.213158
2,CUST000003,Female,64,1,Yes,No,5,No,Fiber Optic,No,...,Credit Card,103.43,561.13,0,4,Yes,0-1 Year,High,Low,112.226000
3,CUST000004,Female,28,0,No,No,46,No,Fiber Optic,Yes,...,Credit Card,88.81,4107.41,2,1,Yes,2-4 Years,High,Medium,89.291522
4,CUST000005,Female,69,1,No,No,4,Yes,Fiber Optic,No,...,Credit Card,66.66,296.04,1,5,Yes,0-1 Year,Medium,Low,74.010000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             10000 non-null  str
 1   Gender                 10000 non-null  str
 2   Age                    10000 non-null  int64
 3   SeniorCitizen          10000 non-null  int64
 4   Partner                10000 non-null  str
 5   Dependents             10000 non-null  str
 6   TenureMonths           10000 non-null  int64
 7   PhoneService           10000 non-null  str
 8   InternetService        10000 non-null  str
 9   OnlineSecurity         10000 non-null  str
 10  OnlineBackup           10000 non-null  str
 11  DeviceProtection       10000 non-null  str
 12  TechSupport            10000 non-null  str
 13  StreamingTV            10000 non-null  str
 14  StreamingMovies        10000 non-null  str
 15  Contract               10000 non-null  str
 16  PaymentMethod          10000 non-null  str
 17  MonthlyCharges         10000 non-null  float64
 18  TotalCharges           10000 non-null  float64
 19  SupportTickets         10000 non-null  int64
 20  SatisfactionScore      10000 non-null  int64
 21  Churn                  10000 non-null  str
 22  TenureGroup            10000 non-null  str
 23  MonthlyChargeCategory  10000 non-null  str
 24  SupportLevel           10000 non-null  str
 25  AverageMonthlySpend    10000 non-null  float64
dtypes: float64(3), int64(5), str(18)
memory usage: 2.0 MB

In [6]:
df["Churn"] = df["Churn"].map({
    "No":0,
    "Yes":1
})

In [7]:
df["Churn"].value_counts()

Churn
1    5326
0    4674
Name: count, dtype: int64

In [8]:
df.drop("CustomerID", axis=1, inplace=True)

In [9]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

In [10]:
categorical_cols = X.select_dtypes(include="object").columns

categorical_cols

/var/folders/yy/96p36gl92dn47gqzrtvgrfsc0000gn/T/ipykernel_16936/3824915372.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include="object").columns

Index(['Gender', 'Partner', 'Dependents', 'PhoneService', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod',
       'TenureGroup', 'MonthlyChargeCategory', 'SupportLevel'],
      dtype='str')

In [11]:
categorical_cols = X.select_dtypes(include=["object", "category"]).columns

categorical_cols

/var/folders/yy/96p36gl92dn47gqzrtvgrfsc0000gn/T/ipykernel_16936/1111965689.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object", "category"]).columns

Index(['Gender', 'Partner', 'Dependents', 'PhoneService', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod',
       'TenureGroup', 'MonthlyChargeCategory', 'SupportLevel'],
      dtype='str')

In [12]:
X = pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True
)

In [13]:
df.head

<bound method NDFrame.head of       Gender  Age  SeniorCitizen Partner Dependents  TenureMonths  \
0     Female   19              0     Yes        Yes            14
1     Female   55              0     Yes         No            57
2     Female   64              1     Yes         No             5
3     Female   28              0      No         No            46
4     Female   69              1      No         No             4
...      ...  ...            ...     ...        ...           ...
9995    Male   64              1      No         No            65
9996  Female   43              0     Yes        Yes            33
9997    Male   31              0     Yes        Yes            12
9998    Male   72              1      No         No            28
9999    Male   69              1      No         No            70

     PhoneService InternetService       OnlineSecurity         OnlineBackup  \
0             Yes           Cable                   No                  Yes
1              No     Fiber Optic                   No                   No
2              No     Fiber Optic                   No                  Yes
3              No     Fiber Optic                  Yes                  Yes
4             Yes     Fiber Optic                   No                  Yes
...           ...             ...                  ...                  ...
9995          Yes     Fiber Optic                  Yes                  Yes
9996           No             DSL                   No                   No
9997          Yes         Unknown  No internet service  No internet service
9998          Yes     Fiber Optic                  Yes                  Yes
9999          Yes             DSL                   No                  Yes

      ...     PaymentMethod MonthlyCharges TotalCharges SupportTickets  \
0     ...  Electronic Check          63.94       902.51              2
1     ...  Electronic Check          72.51      4116.15              0
2     ...       Credit Card         103.43       561.13              0
3     ...       Credit Card          88.81      4107.41              2
4     ...       Credit Card          66.66       296.04              1
...   ...               ...            ...          ...            ...
9995  ...       Credit Card          67.76      4407.62              1
9996  ...       Credit Card          20.87       686.03              2
9997  ...       Credit Card          30.49       403.41              1
9998  ...  Electronic Check          88.81      2545.12              0
9999  ...  Electronic Check          70.00      4945.74              1

     SatisfactionScore Churn  TenureGroup  MonthlyChargeCategory  \
0                    5     1    1-2 Years                 Medium
1                    3     0    4-6 Years                   High
2                    4     1     0-1 Year                   High
3                    1     1    2-4 Years                   High
4                    5     1     0-1 Year                 Medium
...                ...   ...          ...                    ...
9995                 3     0    4-6 Years                 Medium
9996                 4     0    2-4 Years                    Low
9997                 2     1     0-1 Year                    Low
9998                 5     1    2-4 Years                   High
9999                 1     1    4-6 Years                 Medium

      SupportLevel  AverageMonthlySpend
0           Medium            64.465000
1              Low            72.213158
2              Low           112.226000
3           Medium            89.291522
4              Low            74.010000
...            ...                  ...
9995           Low            67.809538
9996        Medium            20.788788
9997           Low            33.617500
9998           Low            90.897143
9999           Low            70.653429

[10000 rows x 25 columns]>

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [15]:
print("Training Features:", X_train.shape)
print("Testing Features :", X_test.shape)
print("Training Target  :", y_train.shape)
print("Testing Target   :", y_test.shape)

Training Features: (8000, 39)
Testing Features : (2000, 39)
Training Target  : (8000,)
Testing Target   : (2000,)

In [16]:
numerical_cols = X_train.select_dtypes(include=["int64", "float64"]).columns
scaler = StandardScaler()

In [17]:
X_train[numerical_cols] = scaler.fit_transform(
    X_train[numerical_cols]
)

X_test[numerical_cols] = scaler.transform(
    X_test[numerical_cols]
)

In [18]:
X_train.head()

,Age,SeniorCitizen,TenureMonths,MonthlyCharges,TotalCharges,SupportTickets,SatisfactionScore,AverageMonthlySpend,Gender_Male,Partner_Yes,...,PaymentMethod_Credit Card,PaymentMethod_Electronic Check,PaymentMethod_Mailed Check,TenureGroup_1-2 Years,TenureGroup_2-4 Years,TenureGroup_4-6 Years,MonthlyChargeCategory_Low,MonthlyChargeCategory_Medium,SupportLevel_Low,SupportLevel_Medium
6132,-0.595881,-0.695866,0.088029,-1.770765,-0.850814,0.611396,1.407847,-1.612619,False,True,...,False,False,False,False,True,False,True,False,False,True
6319,-0.046524,-0.695866,1.498648,0.850009,2.022055,-0.267836,-0.698920,0.852780,True,True,...,True,False,False,False,False,True,False,False,True,False
7750,-1.584725,-0.695866,-0.241116,1.158124,0.270882,-0.267836,0.003336,1.068924,False,True,...,False,True,False,False,True,False,False,False,True,False
6933,-0.156395,-0.695866,0.793338,1.797260,1.916135,0.611396,1.407847,1.681459,False,True,...,False,True,False,False,False,True,False,False,False,True
162,-1.694596,-0.695866,-1.322591,0.885941,-1.006546,-1.147068,-0.698920,0.600553,False,True,...,False,False,False,False,False,False,False,False,True,False

In [19]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 8000 entries, 6132 to 4142
Data columns (total 39 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Age                                   8000 non-null   float64
 1   SeniorCitizen                         8000 non-null   float64
 2   TenureMonths                          8000 non-null   float64
 3   MonthlyCharges                        8000 non-null   float64
 4   TotalCharges                          8000 non-null   float64
 5   SupportTickets                        8000 non-null   float64
 6   SatisfactionScore                     8000 non-null   float64
 7   AverageMonthlySpend                   8000 non-null   float64
 8   Gender_Male                           8000 non-null   bool
 9   Partner_Yes                           8000 non-null   bool
 10  Dependents_Yes                        8000 non-null   bool
 11  PhoneService_Yes                      8000 non-null   bool
 12  InternetService_DSL                   8000 non-null   bool
 13  InternetService_Fiber Optic           8000 non-null   bool
 14  InternetService_Unknown               8000 non-null   bool
 15  OnlineSecurity_No internet service    8000 non-null   bool
 16  OnlineSecurity_Yes                    8000 non-null   bool
 17  OnlineBackup_No internet service      8000 non-null   bool
 18  OnlineBackup_Yes                      8000 non-null   bool
 19  DeviceProtection_No internet service  8000 non-null   bool
 20  DeviceProtection_Yes                  8000 non-null   bool
 21  TechSupport_No internet service       8000 non-null   bool
 22  TechSupport_Yes                       8000 non-null   bool
 23  StreamingTV_No internet service       8000 non-null   bool
 24  StreamingTV_Yes                       8000 non-null   bool
 25  StreamingMovies_No internet service   8000 non-null   bool
 26  StreamingMovies_Yes                   8000 non-null   bool
 27  Contract_One year                     8000 non-null   bool
 28  Contract_Two year                     8000 non-null   bool
 29  PaymentMethod_Credit Card             8000 non-null   bool
 30  PaymentMethod_Electronic Check        8000 non-null   bool
 31  PaymentMethod_Mailed Check            8000 non-null   bool
 32  TenureGroup_1-2 Years                 8000 non-null   bool
 33  TenureGroup_2-4 Years                 8000 non-null   bool
 34  TenureGroup_4-6 Years                 8000 non-null   bool
 35  MonthlyChargeCategory_Low             8000 non-null   bool
 36  MonthlyChargeCategory_Medium          8000 non-null   bool
 37  SupportLevel_Low                      8000 non-null   bool
 38  SupportLevel_Medium                   8000 non-null   bool
dtypes: bool(31), float64(8)
memory usage: 804.7 KB

In [20]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

# Data Preprocessing Summary

## Steps Performed

- Converted the target variable (`Churn`) into numeric values.
- Removed the `CustomerID` column.
- Separated features and target.
- Applied One-Hot Encoding to categorical variables.
- Split the dataset into training and testing sets using an 80:20 ratio.
- Standardized numerical features using `StandardScaler`.
- Saved the processed datasets for model training.

## Result

The dataset is fully prepared for machine learning.